# Generated by Django 4.2.2 on 2023-06-16 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emerytura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prognoza_emerytury', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaPracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okres_zatrudnienia', models.CharField(max_length=100)),
                ('rodzaj_umowy', models.CharField(max_length=100)),
                ('stanowisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OkresNiepracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=100)),
                ('data_poczatku', models.DateField()),
                ('data_konca', models.DateField()),
                ('historia_pracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historiapracy')),
            ],
        ),
        migrations.CreateModel(
            name='OsobisteDane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('data_urodzenia', models.DateField()),
                ('adres', models.CharField(max_length=200)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pracodawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skladki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField()),
                ('miesiac', models.IntegerField()),
                ('skladki', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historia_pracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historiapracy')),
            ],
        ),
        migrations.CreateModel(
            name='Zarobki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField()),
                ('miesiac', models.IntegerField()),
                ('zarobki', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historia_pracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historiapracy')),
            ],
        ),
        migrations.DeleteModel(
            name='app_user',
        ),
        migrations.AddField(
            model_name='historiapracy',
            name='pracodawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pracodawca'),
        ),
        migrations.AddField(
            model_name='historiapracy',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
