# Generated by Django 4.2.2 on 2023-06-21 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_contributions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetirementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirement_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.contribution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_worked', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('employment_period', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='emerytura',
            name='uzytkownik',
        ),
        migrations.RemoveField(
            model_name='historiapracy',
            name='pracodawca',
        ),
        migrations.RemoveField(
            model_name='historiapracy',
            name='uzytkownik',
        ),
        migrations.RemoveField(
            model_name='okresniepracy',
            name='historia_pracy',
        ),
        migrations.RemoveField(
            model_name='osobistedane',
            name='uzytkownik',
        ),
        migrations.RemoveField(
            model_name='skladki',
            name='historia_pracy',
        ),
        migrations.RemoveField(
            model_name='zarobki',
            name='historia_pracy',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Emerytura',
        ),
        migrations.DeleteModel(
            name='HistoriaPracy',
        ),
        migrations.DeleteModel(
            name='OkresNiepracy',
        ),
        migrations.DeleteModel(
            name='OsobisteDane',
        ),
        migrations.DeleteModel(
            name='Pracodawca',
        ),
        migrations.DeleteModel(
            name='Skladki',
        ),
        migrations.DeleteModel(
            name='Zarobki',
        ),
        migrations.AddField(
            model_name='workedlist',
            name='worked_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workedtime'),
        ),
    ]
